### PR TITLE
Input content HTMLmodule

### PR DESCRIPTION
**Pull request by Tychodewaard**
free extensions instead of free extension

### CODE REVIEW

**Comment by bdukes** [comment]
@Tychodewaard you'll want to create a new branch pointing to b593fb1 (the commit fixing the typo), and then edit this PR to be based on that branch instead of [master](https://github.com/Tychodewaard/DNNDocs/tree/master).

**Comment by Tychodewaard** [comment]
I deleted the typo and renamed to htmlcontent. I hope this PR is ok now. (Sorry, not a lot of experience yet in Github). Next stop is creating branches...

**Comment by dnndev** [comment]
Thanks @Tychodewaard. Since the HTML module topic is a new topic, please allow us some time for review. In the meantime, feel free to open another separate pull request to fix that typo, if you haven't done so already.

**Comment by Tychodewaard** [comment]
Well, I want to edit: https://www.dnndocs.com/content/content-managers/extensions/content-managers-extensions-overview/index.html
On https://github.com/DNNCommunity/DNNDocs/tree/master/content/content-managers I can get to that file as I can click on extentions.
In my newly created branche https://github.com/Tychodewaard/DNNDocs/tree/master/content/content-managers I don't see that link.

**Comment by dnndev** [comment]
I found it in one of your branches: https://github.com/Tychodewaard/DNNDocs/tree/CBPSC-patch-1/content/content-managers

Perhaps you need to re-sync your fork?

**Comment by dnndev** [comment]
@Tychodewaard I think I know what happened. When you fixed this PR by removing the "typo fix" file, you ended up deleting that file from your master branch. That's why it is missing. I will go ahead and fix that typo in our docs, so you don't have to worry about getting that corrected. 

Once we've done that, you should re-sync your fork so it matches our repo again. Here are a couple of links you may find helpful detailing how to do it. The first is a how-to using your browser. The second gives you a command-line approach if you have git installed locally.

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

https://help.github.com/en/articles/syncing-a-fork

**Comment by dnndev** [comment]
I'm closing this PR @Tychodewaard. We look forward to the new articles you've submitted, but cannot merge this PR because the file `content/content-managers/extensions/content-managers-extensions-overview/index.md` was deleted. Merging would delete this file from our repo. 

I understand you will be working with @CBPSC for some Git instruction and look forward to the new pull requests. Please create 1 pull request for each new article and for each change/fix. Thanks :)

**Pull request closed without merging**
