### PR TITLE
Updated Git Ignore file to allow 'Releases' folder

### PR DESCRIPTION
**Pull request by CBPSC**
This PR fixes what needed to be fixed in PR #282 (Please close that one). 

The Git ignore file had statements in it filtering out the terms "Release" and "Releases" and we have a folder named "Releases" that provides links to the releases. I commented out the line causing the Releases folder to be ignored. This then brought the "Releases" folder back to life so-to-speak (it wasn't grey in VS Code anymore). I also updated the index.md to follow the format of the "Product Versions" page we just updated in PR #298 

Please note that the "Releases" folder and the "Product Versions" folder have basically identical content now and one of them should likely be removed. This will need to be discussed at the Docs leadership meeting.

### CODE REVIEW

**Comment by CBPSC** [comment]
This PR has been updated as requested. @nvisionative

**Comment by CBPSC** [comment]
Noticed the /**/ didn't make it so I added it ;-)

**Comment by CBPSC** [comment]
Gonna close this one and resubmit a new one.

**Comment by nvisionative** [comment]
@CBPSC we now have more issues (conflicts) with this PR.  Can you see what may be the problem?  As soon as the conflicts are resolved, I'll pull local and test against plugins Release(s) folders to make sure they are still not tracked.  Thanks!

**Pull request closed without merging**
