### PR TITLE
Updated minimum requirements

### PR DESCRIPTION
**Pull request by mitchelsellers**
Updated requirements to reflect recent changes in DNN Platform.  Additionally added a note on the recommended environment to differentiate between developer & actual environment requirements.

### CODE REVIEW

**Comment by ohine** [comment]
Closes: https://github.com/dnnsoftware/Dnn.Platform/issues/2786
Closes: https://github.com/dnnsoftware/Dnn.Platform/issues/2784

**Comment by david-poindexter** [comment]
@mitchelsellers our apologies, but things have moved around quite a bit since this PR was created.  Would you mind updating this PR to reflect the proposed changes in the new file/location?  We'll try to merge quickly now that we are so close to releasing 9.4.0.

**Comment by mitchelsellers** [comment]
Will do, might not be until Tuesday

**Comment by mitchelsellers** [comment]
Closing this in favor of the new submitted #372

**Pull request closed without merging**
