### PR TITLE
Change suggested upgrade path for less maintenance

### LINKED ISSUE #497: Updade suggested upgrade path to minimize maintenance
## Description of documentation change
As discussed in slack, we now release much more often than before and updating the suggested upgrade path is something we would need to do very often. We discussed changing the last row to "latest 9.x.x release" and point that to the general release page.

## Existing documentation URL (if applicable)
https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path/index.html#dnn-platform-suggested-upgrade-path

## Additional context
I will submit a PR for that in a few minutes...

### PR DESCRIPTION
**Pull request by valadas**
Closes #497

Changes last row to point to general releases page.

### CODE REVIEW

**Comment by david-poindexter** [comment]
@valadas see [my comment on the referenced issue](https://github.com/DNNCommunity/DNNDocs/issues/497#issuecomment-625566279).  I would be interested in hearing from the other DNN Docs core team members on this one before we merge.  We also have a pending PR #488 on hold awaiting the release of 9.6.1.
cc: @dnndev @donker @CBPSC @patrickryan79

**Comment by valadas** [comment]
Yeah, well it is here, so I let you guys discuss and decide, I won't be mad if it is refused :)

IMO this would make maintenance of this page easier since we release much more often than before and we often forget to update this page. That way we only need to update if we know there is a special case that justifies a different stepping point other than the latest release.

**Comment by dnndev** [comment]
@valadas Are you saying that no matter what, upgrading from v9.3.2 to the latest version directly is the best upgrade?

**Comment by valadas** [comment]
Well stopping points in the upgrade paths are more rare than just going directly to the last same major version. So we would not need to update this document sooo often. We release way more often than before. This would help to not forget to update this document and we do want to promote running the latest version. It would just be less maintenance, but if we know there is some issue that justifies a new step point in the upgrade path, then we do edit the document...

**Comment by dnndev** [comment]
My belief is that the documentation should generally be as specific as possible (irony noted). I don't think we need to say upgrade from 9.3.2 to 9.4.0, then later amend that to 9.4.1, 9.4.2 etc. How about we say go from 9.3.2 to 9.4.x - then later to 9.5.x. That reduces maintenance to only minor version steps. While the release cadence is increased, the speed of minor version releases is slow enough that I don't think the burden would be too great.

**Comment by david-poindexter** [comment]
My problem with these recommendations is that it is not just text we are dealing with here.  These are hyperlinks that need to reduce confusion for the person needing to quickly access the correct release for the upgrade path they are working on.  It has never really been a problem the way it is.

**Comment by jeremy-farrance** [comment]
At this point in time, 9.03.02 to the "Latest Release" is correct (9.06.01 as I write this). I prefer the goal is to always keep it this way until we reach an **obvious** point where necessity introduces a new "upgrading waypoint." There needs to be a good reason for introducing an in-between upgrade point since it can add a lot of time to the work involved in managing a site. And I very strongly agree with the idea of not needing to remember to update this part of the docs... until there is once again an **obvious** need.

**Comment by david-poindexter** [comment]
Thanks for the input everyone.  I'm going to go ahead and close this PR in favor of the same mode of operation we have had since like the beginning of time (aka, when this upgrade path was originally created and contributed by @hismightiness).  @jeremy-farrance thanks for so eloquently describing the philosophy around "upgrading waypoint".  That's a great way to think about it.

**Pull request closed without merging**
