### PR TITLE
Get links and related-topics in the UI

### PR DESCRIPTION
**Pull request by donker**
This PR will render links and related topics in a hidden div at the end of each article. Then, the front end script will move those links to the sidebar nav on the right.

### CODE REVIEW

**Comment by donker** [comment]
> 
> 
> @donker I am a bit confused as to why this is in the GitHubStats plugin. It doesn't seem relevant to GitHub stats at all. That said, it looks like a really nice enhancement - woo hoo! Would you like to move this to a separate plugin project?

Yes, I was struck by the rather unfortunate naming of that plugin project. In the interest of not wasting more time I did it this way. If you like, feel free to create a new project and move the code in there.

**Comment by donker** [comment]
OK, fixed it ...

**Comment by david-poindexter** [comment]
@donker we'll need to revisit this in another PR - something when awry here and I didn't have time to test locally.  If you want to get on a call together to talk through this together, I can do so.  Just ping me on Slack.

**Comment by donker** [comment]
It works here ...

**Pull request merged**
