### PR TITLE
Add page level contributors, last edit date, time to read indicator, and GitHub authentication

### LINKED ISSUE #155: Add support for page level GitHub contributors attribution
## Description of problem
Currently, we have **Top Contributors** on the home page.  We should add support for page level GitHub contributor attribution.

## Description of solution
It would be nice to do something like Microsoft does for their online docs.  Below the title of each page/article, they have GitHub contributor avatar links listed horizontally.  I propose we do the same thing for the DNNDocs site.

## Description of alternatives considered
n/a

## Screenshots
ScreenCapture_ 2019-03-29 05 24 PM _2213

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### LINKED ISSUE #159: Add date below page title on which the last page commit was processed
## Description of problem
Currently, it is impossible to discern (from a DNNDocs page) when the last update to the page was made.  It would be nice to see the date on which the last commit was processed.

## Description of solution
It would be nice to do something like Microsoft does for their online docs.  Below the title of each page/article, they display the date on which the last commit was processed.  I propose we do the same thing for the DNNDocs site.

## Description of alternatives considered
n/a

## Screenshots
ScreenCapture_ 2019-03-29 05 24 PM _2213

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### LINKED ISSUE #164: Add Support for GitHub API Basic Authentication via Personal Access Token
## Description of problem
To retrieve **Top Contributors** for the home page, we were able to get away with a unauthenticated API calls, since the call is only made once at docfx build time.  However, in support of #155 and #159, a GitHub API call will be made for every processed conceptual document.  Therefore, to avoid hitting GitHub API [rate limits](https://developer.github.com/v3/#rate-limiting), we need to use authenticated API calls.

## Description of solution
Add an untracked **github.json** file to the root of this project.  This file will be in the following format:

`
{
  "access_token": "replactThisWithYourGitHubPersonalAccessToken"
}
`

When setting up your GitHub Personal Access Token, you will need to make sure it has the appropriate level of read access for **repo**.  See this page for instructions on how to setup a Personal Access Token.

Since we are recommending and using a read-only Personal Access Token, the above approach is low risk from a security perspective.

## Description of alternatives considered
Local environment variables were considered, but this is much more difficult to document for all the flavors of operating systems and it would also have increased the complexity of coding in the custom **PageStatsDocumentProcessor** plugin.

Another option to look into would be Azure Key Vault (or similar service).  However, this may cause some other challenges.

## Screenshots
n/a

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### PR DESCRIPTION
**Pull request by nvisionative**
Resolves #155 
Resolves #159 
Resovles #160 
Resolves #164 

Screenshot 2019-04-01 03 43 30

### CODE REVIEW

**Comment by hismightiness** [comment]
Great stuff here!

**Comment by mhenricus** [comment]
Nice, but how to do this? Which setting(s) to use to have this added? Is there any manual for all the (json) settings?

**Comment by david-poindexter** [comment]
> Nice, but how to do this? Which setting(s) to use to have this added? Is there any manual for all the (json) settings?

@mhenricus thanks.  All the details on how these features were accomplished are within this pull request.  See the [Files changed](https://github.com/DNNCommunity/DNNDocs/pull/166/files) tab.  There is no documentation on this documentation project itself, but it is built using `DocFx` and there is plenty of documentation out there about it.  It is the same base Microsoft uses for their documentation projects.

**Comment by mhenricus** [comment]
Hello David, I haven't found (yet) documentation about how to use this feature. Perhaps you can point me into any direction out there?

**Comment by david-poindexter** [comment]
@mhenricus these features are already built into DNN Docs, so no documentation is necessary - they are part of the docs generated by this project.

Perhaps I am misunderstanding though - are you trying to figure out how to use the features on DNN Docs, or build your own DocFx based project with similar features?  Or something else?

**Comment by mhenricus** [comment]
Ah, I am in the DNN repo. Sorry for the confusion.
I am using docfx command line to generate static html from md files. Is there any way to add something to the docfx.json or markdown files to add the last date modified to the html help?

**Comment by david-poindexter** [comment]
@mhenricus which of the following are you trying to do?

1. Build your own `DocFx` based project with similar features.
2. Work with the `DNN Docs` project to understand it better and participate in this project.
3. Something else. If so, please specify clearly.

This is a pull request from April 2019 and it is related to multiple issues and features.  So, the more clear you can be, the better I may be able to help point you in the right direction.

**Comment by mhenricus** [comment]
I am generating static html from markdown files with docfx. Basically like how it is described in this tutorial: https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project.html

**Comment by david-poindexter** [comment]
@mhenricus - I am sorry, but it is still not totally clear to me.  I'll just assume at this point that `#1` above is your intention.  In that case, you are welcome to view the [file changes](https://github.com/DNNCommunity/DNNDocs/pull/166/files) in this pull request to see how we pulled off this feature.  (In essence, we are using DocFx `postProcessors` and we have a `PageStatsProcessor` to handle page-level stats.)  

For more detailed `DocFx` questions, you will probably be best served to ask those in the [appropriate repo](https://github.com/dotnet/docfx).

**Pull request merged**
