### PR TITLE
Updated Page Title and TOC link name to 'Releases'

### PR DESCRIPTION
**Pull request by CBPSC**
As previously discussed we are opting to update the name of the file "Product Versions" to "Releases" as the page lists the links to the actual release and the release notes.

In this PR I've updated the TOC reference link name + updated the page title and page H1. 

**Note:** I did not update the UID just in case some other pages were referencing the old UID. Didn't want to break any pages.

### CODE REVIEW

**Comment by CBPSC** [comment]
Just noticed where the change to the folder name was not included on this one. Please hold off merging until I figure out why the updated folder name was not sent.

**Comment by dnndev** [comment]
If you rename a file/folder, it is seen as deleting the file/folder and "new" file/folder is added. So you may have to add the "new" files/folders. A `git status` should help here.

**Comment by CBPSC** [comment]
@nvisionative actually found the issue and discussed it in the DNN Docs slack channel. It was because a git ignore command that we are re-thinking of how to implement.

**Comment by CBPSC** [comment]
I'm going to close this one as PR #300 provides the needed update.

**Pull request closed without merging**
