### PR TITLE
Changed last step from 9.5.0 to 9.6.1

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**

### CODE REVIEW

**Comment by david-poindexter** [comment]
@Timo-Breumelhof can you update this to 9..6.1?  And then we hold off until that release (which should be fairly soon.

**Comment by Timo-Breumelhof** [comment]
Sure

**Comment by Timo-Breumelhof** [comment]
@david-poindexter done

**Comment by valadas** [comment]
I think this is good to go now or #498 depending on opinions :)

**Pull request merged**
