### PR TITLE
Add Client Resources article

### PR DESCRIPTION
**Pull request by bdukes**
@david-poindexter [asked me to contribute](https://github.com/dnnsoftware/Dnn.Platform/issues/2273#issuecomment-640245894) docs on using the `async` attribute with scripts, so I've written up this article on the client resource management system within DNN Platform.

Thanks for any edits, I'm sure there's a lot of prose that can be reorganized or cleaned up.  I'm also not sure where in the site's organization you'd want this to be (or if the article needs to be adjusted to fit better into any particular section).

Hope it helps!

### CODE REVIEW

**Comment by david-poindexter** [comment]
@bdukes this is FANTASTIC!!!  Thank you for the wonderful contribution!  I haven't had time to read it thoroughly, but will try to do so later on.  I am not quite sure where this needs to ultimately live, but it would be ideal to split this into two pieces - one for `Features` and one for `Tutorials`.  The `Features` portion should strictly document the feature.  Then the `Tutorials` portion can document the "how to".  Thoughts?

**Comment by bdukes** [comment]
On the Performance features page, we could list the following:
* JS and CSS file combination
* JS and CSS file minification
* JS and CSS file de-duplication

And then on the general features page, we could list the following:
* Client resource (JS & CSS) management

Or do you want a client resources features page, with things like:
* Resource prioritization/ordering
* Resource placement (`<head>` vs. `<body>` top vs. `<form>` bottom)
* JS library versioning
* JS library CDN (via setting without UI)

**Comment by david-poindexter** [comment]
@bdukes I am thinking we should probably create a "Client Resources" subpage under "Performance" in the `Features` section.

**Comment by bdukes** [comment]
@david-poindexter I've added a features page, is that like what you were thinking?

**Comment by david-poindexter** [comment]
@bdukes yes - perfect!

**Comment by bdukes** [comment]
I also just added another section about the `DnnCssExclude` theme object.

**Comment by david-poindexter** [comment]
@bdukes do want me to go ahead and merge this PR and look for future PRs for the remaining pieces?  Or just keep everything in this PR?

**Comment by bdukes** [comment]
I'd say go ahead and merge it.  What other pieces are you looking for?

**Comment by david-poindexter** [comment]
@bdukes my apologies - thought you had more on your list for this.  I'll go ahead and merge, but someone will need to update the table of contents file for left navbar.m in a future PR.

**Pull request merged**
