### PR TITLE
Localization Issue #486

### PR DESCRIPTION
**Pull request by SmallMistake**
Continuation of the request for help translating a blog on Localization to a guide under the content management tab:
https://github.com/DNNCommunity/DNNDocs/issues/486 (Localization)

I based it largely off of the guide outlined in the thread and my very limited experience so I might have overlooked something. Let me know if there are any areas that you think need any more explanation.

### CODE REVIEW

**Comment by SmallMistake** [comment]
Fixed Image Links by including images with project

**Comment by valadas** [comment]
@david-poindexter is /images/something.jpg ok here or do they need to be ../images/something.jpg ?

**Comment by SmallMistake** [comment]
I don't know for sure. I just copied what another page was doing and flipped it into preview mode to make sure it works. Since it worked in preview mode it probably should be fine.

**Review by david-poindexter — APPROVED** [review]
My sincere apologies for the delayed response.  I just discovered an email rule issue on my machine for this repo.  I have reviewed the PR and will approve/merge it.  Thanks @SmallMistake for the contribution - this is GREAT!  🎉

**Comment by david-poindexter** [comment]
@valadas as a reminder, we still have this CI/CD issue to look into to ensure success with publishing this.  I had forgotten that, so let me know when you have some time and we can double-team this one.  I think we should hold off merging this until we get the build issue resolved.  Otherwise, it will not be published on the site.

**Comment by valadas** [comment]
@david-poindexter yeah, I honestly don't remember what the issue was, I'll submit a test PR just to get fresh build logs as the existing ones expired :)

**Pull request merged**
