### PR TITLE
Fix homepage links with /guides/

### PR DESCRIPTION
**Pull request by Accuraty**
Not sure I am doing this right, someone able to test/verify this?
 
Recently the path /guides/ was removed, so /tutorials and others are now directly below http://localhost:8080/content/
 
I found that the home page was being created from this template and manually fixed the links. Seems to work for me locally.

This should fix it so that links that still have /guides/ are pointing to the current/real pages.
 
Example from Home in the Designers section, Creating Themes currently goes here
https://www.dnndocs.com/content/guides/tutorials/themes/creating-themes/designers-creating-themes-overview/index.html
 
The above is WRONG, it should go here.
https://www.dnndocs.com/content/tutorials/themes/creating-themes/designers-creating-themes-overview/index.html

### CODE REVIEW

**Comment by Accuraty** [comment]
My apologies, I appear to have done my steps in the slightly wrong order and my updates from yesterday (without change) are getting repeated in this merge.

**Comment by david-poindexter** [comment]
@Accuraty just create a separate branch (from master) and then copy your changes from this branch to the new one.

**Comment by david-poindexter** [comment]
Or I can manually modify this branch if you'd like.

**Comment by Accuraty** [comment]
Done, I just deleted the two files in this commit.

**Comment by Accuraty** [comment]
Ooh, yuck, didn't realize delete of the toc.md was an action, hmm....

**Comment by david-poindexter** [comment]
Well, you now have a conflict with `content/tutorials/toc.md` that needs to be resolve in order for this to be merged.  I would highly recommend doing a new/fresh branch (from master) and simply copying your changes for the index template to the new branch.

**Comment by Accuraty** [comment]
will do, thanks

**Comment by Accuraty** [comment]
redoing this ...

**Comment by david-poindexter** [comment]
hehe, thanks!

**Pull request closed without merging**
