### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nvisionative**
Update docfx command to build and serve.

### CODE REVIEW

**Comment by nvisionative** [comment]
`docfx --serve` errors out on Mac.  This may have something to do with DNN.Platform not building though, so let me try removing DNN.Platform and see what happens.  That may not be about to build on a Mac - which I would find odd because it is only reading XML, right?

**Comment by dnndev** [comment]
You would think, but perhaps DocFX loads the solution and thus requires .NET to read it.

**Comment by nvisionative** [comment]
I tested removing my **DNN.Platform** folder and now `docfx --serve` works just fine.  I'd say we close this PR and figure out what needs to be done to get this to build the **DNN.Platform** folder on OS X.

**Comment by nvisionative** [comment]
Issue #127 created to document this issue.

**Pull request closed without merging**
