### PR TITLE
Minor revisions, fixes, and a new Overview page

### PR DESCRIPTION
**Pull request by jeremy-farrance**
Added Configure Your Site overview page (a start)
Fixed home page link to Configure Your Site overview
Removed unused subpage duplicate folder/index.md
Fixed up Configure Your Site page; adj headings, fixed !Note, corrected node/attribute formatting

### CODE REVIEW

**Comment by jeremy-farrance** [comment]
Fixed/resolved the conflict created by a more recent change to the home page index.html.tmpl

**Comment by jeremy-farrance** [comment]
Anything I can do to get this one approved or pushed thru? I'd be willing to delete it and do it part in smaller pieces that would be easier to investigate or verify.

**Comment by dnndev** [comment]
There are conflicts that would prevent a merge.  It would be better if you could split them apart into more atomic changes.

**Comment by jeremy-farrance** [comment]
> There are conflicts that would prevent a merge. It would be better if you could split them apart into more atomic changes.

I did already resolve the conflict as noted above. If it is still open this weekend, I will split it up. Thanks! - Jeremy

**Comment by jeremy-farrance** [comment]
Can someone please take another look at this? These are very minor changes, no conflicts. If there is still a conflict that I do not see or understand, could you please let me know what it is?

**Pull request merged**
